version: '3'
services: 
  swapper-prod-www-deploy:
    container_name: swapper-prod-www-deploy
    build: 
      context: "."
      dockerfile: "dockerfile.deploy"
    volumes: 
      - "~/.aws:/root/.aws"
    command: s3 cp . s3://www.swapper.fi --recursive
  swapper-prod-deploy:
    container_name: swapper-prod-deploy
    build: 
      context: "."
      dockerfile: "dockerfile.deploy"
    volumes: 
      - "~/.aws:/root/.aws"
    command: s3 cp . s3://swapper.fi --recursive