version: '3'
services: 
  swapper-staging-www-deploy:
    build: 
      context: "."
      dockerfile: "dockerfile.deploy"
    environment: 
      - AWS_ACCESS_KEY_ID=${AWS_ACCESS_KEY_ID}
      - AWS_SECRET_ACCESS_KEY=${AWS_SECRET_ACCESS_KEY}
      - AWS_DEFAULT_REGION=${AWS_DEFAULT_REGION}
    command: s3 cp . s3://www.staging.swapper.fi --recursive
  swapper-staging-deploy:
    build: 
      context: "."
      dockerfile: "dockerfile.deploy"
    environment: 
      - AWS_ACCESS_KEY_ID=${AWS_ACCESS_KEY_ID}
      - AWS_SECRET_ACCESS_KEY=${AWS_SECRET_ACCESS_KEY}
      - AWS_DEFAULT_REGION=${AWS_DEFAULT_REGION}
    command: s3 cp . s3://staging.swapper.fi --recursive