FROM node:15.13.0-alpine3.10 as builder
WORKDIR /app
RUN apk update && apk add git openssl


COPY package.json .
COPY .git .
COPY tsconfig.json .
RUN yarn
COPY src/ ./src/
COPY public/ ./public/
RUN yarn build

FROM amazon/aws-cli:latest
COPY --from=builder ./app/build/ .